// Auto-generated from is_akisi_senaryolari_60_sektor.xlsx
// 70 industries, 140+ templates, industry-specific AI context

export type Industry = {
  id: number;
  category: string;
  name: string;
  scenarios: string[];
  templates: { name: string; content: string; target: string; trigger: string }[];
  integrations: string[];
  quickActions: string[];
  benefitScore: number;
  teamScore: number;
};

export type IndustryCategory = {
  name: string;
  industries: Industry[];
};

export const INDUSTRIES: Industry[] = [
  {
    id: 1,
    category: 'İnşaat & Mimarlık',
    name: 'İnşaat Şirketi',
    scenarios: ['Şantiye günlük ilerleme raporu: Kalıp işleri %60 tamamlandı, beton dökümü yarın planlanıyor, hava durumu kontrol edildi', 'Taşeron koordinasyonu: Elektrikçi ve tesisatçı ekiplerin aynı katta çakışma riski, program güncellenmeli', 'Malzeme tedarik takibi: Demir siparişi 3 gün gecikti, alternatif tedarikçiye acil teklif istenmeli'],
    templates: [{ name: 'Durum Güncelleme', content: '⚠️ Gecikme Bildirimi: [Malzeme/İş] [X] gün gecikme | Etki: [açıklama] | Aksiyon: [plan]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Google Calendar', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Calendar', 'WhatsApp Business', 'Google Drive'],
    quickActions: ['Şantiye günlük ilerleme raporu', 'Taşeron koordinasyonu', 'Malzeme tedarik takibi'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 2,
    category: 'İnşaat & Mimarlık',
    name: 'Mimarlık Ofisi',
    scenarios: ['Proje revizyonu: Müşteri mutfak planını değiştirmek istiyor, revize çizim 2 gün içinde teslim edilmeli', 'Belediye ruhsat süreci: Eksik evrak bildirimi geldi, statik rapor ve zemin etüdü güncellenmeli', '3D render onayı: İç mimar render hazırladı, müşteriye sunum öncesi ekip içi değerlendirme yapılmalı'],
    templates: [{ name: 'Sabah Brifingi', content: '📐 Ruhsat Takip: Başvuru No [X] | Durum: [bekleyen/onay/red] | Eksik: [evrak listesi]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'AutoCAD/Revit', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['AutoCAD/Revit', 'Trello/Asana', 'Dropbox'],
    quickActions: ['Proje revizyonu', 'Belediye ruhsat süreci', '3D render onayı'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 3,
    category: 'İnşaat & Mimarlık',
    name: 'Peyzaj/Çevre Düzenleme',
    scenarios: ['Proje sahası sulama sistemi kurulumu: Damla sulama hattı çekildi, basınç testi bugün yapılacak', 'Bitki tedarik: Mevsimlik çiçek siparişi fidanlıktan çıktı, yarın teslimat bekleniyor', 'Müşteri bahçe bakım sözleşmesi yenileme: 12 aylık bakım teklifi hazırlanacak'],
    templates: [{ name: 'İlerleme Raporu', content: '🌳 Bakım Teklifi: [Müşteri] | Kapsam: [detay] | Süre: [ay] | Tutar: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'Google Maps', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Maps', 'WhatsApp Grup', 'Excel/Sheets'],
    quickActions: ['Proje sahası sulama sistemi kurulumu', 'Bitki tedarik', 'Müşteri bahçe bakım sözleşmesi yenileme'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 4,
    category: 'Sağlık',
    name: 'Diş Kliniği',
    scenarios: ['Sabah brifingi: Bugün 14 randevu var, 3 implant cerrahisi, sterilizasyon kontrolü yapıldı', 'Acil hasta: Randevusuz gelen ağrılı hasta, programa sıkıştırılmalı, diğer hastalar bilgilendirilmeli', 'Malzeme stok uyarısı: Kompozit dolgu malzemesi kritik seviyede, acil sipariş verilmeli'],
    templates: [{ name: 'Kontrol Raporu', content: '📦 Stok Uyarısı: [Malzeme] kritik seviye | Mevcut: [adet] | Sipariş: [gerekli adet]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'Randevu Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Randevu Sistemi', 'SMS Hatırlatma', 'Muhasebe Yazılımı'],
    quickActions: ['Sabah brifingi', 'Acil hasta', 'Malzeme stok uyarısı'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 5,
    category: 'Sağlık',
    name: 'Veteriner Kliniği',
    scenarios: ['Sabah vizitleri: 3 yatan hasta kontrolü, serum takibi ve ilaç uygulaması yapılacak', 'Acil operasyon: Trafik kazası köpek, röntgen çekildi, ameliyat kararı verilecek', 'Aşı takip: Bu hafta aşı zamanı gelen 25 hasta sahibine hatırlatma gönderilmeli'],
    templates: [{ name: 'İlk Değerlendirme', content: '💉 Aşı Hatırlatma: Sayın [isim], [hayvan adı] için [aşı türü] zamanı geldi. Randevu: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'PetNet/Vet Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['PetNet/Vet Yazılımı', 'SMS Gateway', 'Online Randevu'],
    quickActions: ['Sabah vizitleri', 'Acil operasyon', 'Aşı takip'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 6,
    category: 'Sağlık',
    name: 'Eczane',
    scenarios: ['Sabah sayımı: Soğuk zincir ilaçlar kontrol edildi, 2 ürünün son kullanma tarihi yaklaşıyor', 'Reçeteli ilaç talebi: Stokta olmayan ilaç için ecza deposuna acil sipariş, hastaya bilgi verilmeli', 'SGK mutabakat: Aylık SGK kesintileri kontrol edilecek, uyuşmayan reçeteler tespit edilmeli'],
    templates: [{ name: 'Günlük Kayıt', content: '📋 Depo Siparişi: [İlaç listesi] | Miktar: [adet] | Aciliyet: [normal/acil] | Depo: [isim]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Ecza Depo Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Ecza Depo Sistemi', 'SGK Medula', 'Barkod Sistemi'],
    quickActions: ['Sabah sayımı', 'Reçeteli ilaç talebi', 'SGK mutabakat'],
    benefitScore: 7,
    teamScore: 6,
  },
  {
    id: 7,
    category: 'Sağlık',
    name: 'Fizyoterapi Merkezi',
    scenarios: ['Günlük seans programı: 18 hasta, 3 yeni hasta değerlendirmesi, cihaz bakım zamanı', 'Hasta ilerleme notu: Diz ameliyatı sonrası 8. seans, ROM ölçümü yapılacak', 'Sigorta onay takibi: 5 hastanın sigorta provizyon onayı bekleniyor'],
    templates: [{ name: 'Vardiya Raporu', content: '📊 Haftalık İlerleme: [Hasta] | Başlangıç: [ölçüm] | Güncel: [ölçüm] | Hedef: [değer]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'Hasta Takip Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Hasta Takip Yazılımı', 'Online Randevu', 'Sigorta Portal'],
    quickActions: ['Günlük seans programı', 'Hasta ilerleme notu', 'Sigorta onay takibi'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 8,
    category: 'Teknoloji',
    name: 'Yazılım Geliştirme',
    scenarios: ['Sprint daily standup: Dün tamamlanan tasklar, bugünkü plan, blocker\'lar tartışılacak', 'Prod\'da bug: Ödeme sayfasında 500 hatası, hotfix branch açıldı, QA testi sonrası deploy', 'Yeni feature planlama: Müşteri dashboard isteği, UX wireframe hazırlanacak, effort estimation yapılacak'],
    templates: [{ name: 'İş Emri', content: '🚀 Deploy Bildirimi: Versiyon [X.Y.Z] | Değişiklikler: [özet] | Rollback planı: [var/yok]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'Jira/Linear', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Jira/Linear', 'GitHub/GitLab', 'Slack'],
    quickActions: ['Sprint daily standup', 'Prod\'da bug', 'Yeni feature planlama'],
    benefitScore: 10,
    teamScore: 10,
  },
  {
    id: 9,
    category: 'Teknoloji',
    name: 'Dijital Pazarlama Ajansı',
    scenarios: ['Müşteri kampanya brifingi: Yeni ürün lansmanı, sosyal medya + Google Ads + influencer planı çıkarılacak', 'Aylık performans raporu: Tüm müşterilerin Google Ads ve Meta reklam metrikleri derlenmeli', 'İçerik takvimi: Gelecek hafta için 15 paylaşım hazırlanacak, tasarımcıya brief verilmeli'],
    templates: [{ name: 'Seans Notu', content: '📝 İçerik Brief: Platform: [X] | Konu: [Y] | Format: [görsel/video/story] | Termin: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'Google Ads', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Ads', 'Meta Business Suite', 'Canva/Figma'],
    quickActions: ['Müşteri kampanya brifingi', 'Aylık performans raporu', 'İçerik takvimi'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 10,
    category: 'Teknoloji',
    name: 'IT Destek / MSP',
    scenarios: ['Sabah ticket kontrolü: 12 açık ticket, 3 kritik (sunucu erişim sorunu), SLA süreleri kontrol edilmeli', 'Yeni müşteri onboarding: 15 bilgisayar kurulumu, Active Directory yapılandırması, VPN ayarları', 'Güvenlik uyarısı: Firewall loglarında şüpheli giriş denemesi tespit edildi, IP bloklama yapılmalı'],
    templates: [{ name: 'Stok Uyarısı', content: '🔒 Güvenlik Bildirimi: [Olay türü] | Zaman: [saat] | Etki: [değerlendirme] | Aksiyon: [plan]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'Zendesk/Freshdesk', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Zendesk/Freshdesk', 'TeamViewer/AnyDesk', 'Microsoft 365'],
    quickActions: ['Sabah ticket kontrolü', 'Yeni müşteri onboarding', 'Güvenlik uyarısı'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 11,
    category: 'Teknoloji',
    name: 'E-ticaret İşletmesi',
    scenarios: ['Sabah sipariş kontrolü: Gece gelen 47 sipariş, 5 iade talebi, kargo entegrasyonu kontrol', 'Stok uyarısı: En çok satan 3 ürün kritik stok seviyesinde, tedarikçiye sipariş verilmeli', 'Kampanya hazırlığı: Hafta sonu %20 indirim kampanyası, banner tasarımı ve e-posta gönderimi'],
    templates: [{ name: 'Üretim Raporu', content: '🏷️ Kampanya Duyurusu: [Kampanya adı] | Tarih: [başlangıç-bitiş] | İndirim: [%] | Ürünler: [liste]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Trendyol/Hepsiburada API', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Trendyol/Hepsiburada API', 'Kargo Entegrasyonu', 'Google Analytics'],
    quickActions: ['Sabah sipariş kontrolü', 'Stok uyarısı', 'Kampanya hazırlığı'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 12,
    category: 'Eğitim',
    name: 'Özel Okul / Kurs Merkezi',
    scenarios: ['Sabah yoklama kontrolü: 3 sınıfta devamsızlık bildirimi, velilere bilgilendirme yapılmalı', 'Sınav hazırlığı: Hafta sonu deneme sınavı, soru bankası hazırlanacak, salon planı yapılacak', 'Veli görüşme günü: 20 veli randevusu, her öğrencinin karne özeti hazırlanmalı'],
    templates: [{ name: 'Çekim Brifingi', content: '📝 Sınav Duyurusu: [Sınav türü] | Tarih: [X] | Saat: [Y] | Kapsam: [konular] | Salon: [Z]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'Okul Yönetim Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Okul Yönetim Sistemi', 'SMS/Push Bildirim', 'Zoom/Teams'],
    quickActions: ['Sabah yoklama kontrolü', 'Sınav hazırlığı', 'Veli görüşme günü'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 13,
    category: 'Eğitim',
    name: 'Dil Okulu',
    scenarios: ['Günlük ders programı: 6 grup dersi, 4 özel ders, ikame öğretmen ayarlaması gerekiyor', 'Seviye tespit sınavı: Yeni kayıt olan 8 öğrenci için placement test yapılacak', 'Sertifika hazırlığı: Kur sonu sınavları yaklaşıyor, sertifika basımı organize edilmeli'],
    templates: [{ name: 'Proje Durumu', content: '📊 İlerleme Raporu: [Öğrenci] | Seviye: [A1-C2] | Devam: [%] | Not Ort: [X] | Öneri: [not]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'LMS Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['LMS Sistemi', 'Zoom', 'WhatsApp Grup'],
    quickActions: ['Günlük ders programı', 'Seviye tespit sınavı', 'Sertifika hazırlığı'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 14,
    category: 'Eğitim',
    name: 'Kreş / Anaokulu',
    scenarios: ['Sabah karşılama: Ateş ölçümü, veli bilgilendirme, günlük aktivite planı kontrol', 'Beslenme takibi: Öğle menüsü hazırlandı, alerji listesi kontrol edildi, mutfak bilgilendirildi', 'Etkinlik hazırlığı: Ayın doğum günü partisi, malzeme listesi ve veli izin formları hazırlanmalı'],
    templates: [{ name: 'Hizmet Raporu', content: '🎂 Etkinlik Bildirimi: [Etkinlik] | Tarih: [X] | İzin Formu: [ekte] | Gerekli: [malzeme]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'Veli İletişim Uygulaması', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Veli İletişim Uygulaması', 'Kamera Sistemi', 'Online Ödeme'],
    quickActions: ['Sabah karşılama', 'Beslenme takibi', 'Etkinlik hazırlığı'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 15,
    category: 'Gıda & Restoran',
    name: 'Restoran / Kafe',
    scenarios: ['Açılış hazırlığı: Mutfak mise en place, garson brifing, günün özel menüsü belirlendi', 'Tedarik kontrolü: Sebze-meyve siparişi geldi, kalite kontrolü yapılacak, eksikler not alınacak', 'Akşam rezervasyonları: 8 masa rezerve, 2 özel gün (doğum günü), hazırlık yapılmalı'],
    templates: [{ name: 'Etkinlik Brifingi', content: '📞 Rezervasyon Onayı: Sayın [isim], [tarih] [saat] [kişi] kişilik rezervasyonunuz onaylandı', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'POS Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['POS Sistemi', 'Yemeksepeti/Getir', 'Reservasyon Yazılımı'],
    quickActions: ['Açılış hazırlığı', 'Tedarik kontrolü', 'Akşam rezervasyonları'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 16,
    category: 'Gıda & Restoran',
    name: 'Pastane / Fırın',
    scenarios: ['Gece üretim raporu: 200 ekmek, 50 poğaça, 30 pasta üretildi, sabah taze ürün tezgaha çıkıyor', 'Özel sipariş takibi: 3 düğün pastası, 5 doğum günü pastası bu hafta, hammadde kontrolü yapılmalı', 'Hijyen kontrolü: Haftalık temizlik checklist\'i, gıda güvenliği belgeleri güncellenmeli'],
    templates: [{ name: 'Sipariş Takip', content: '🧾 Günlük Üretim: [Ürün listesi] | Miktar: [adet] | Satış: [adet] | Fire: [%] | Not: [sorun]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Kasa Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Kasa Sistemi', 'Instagram', 'Sipariş Takip Yazılımı'],
    quickActions: ['Gece üretim raporu', 'Özel sipariş takibi', 'Hijyen kontrolü'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 17,
    category: 'Gıda & Restoran',
    name: 'Catering Firması',
    scenarios: ['Etkinlik brifingi: Yarınki 200 kişilik düğün, menü kesinleşti, ekip ve lojistik planlanacak', 'Mutfak üretim planı: 3 farklı etkinlik için eş zamanlı üretim, zaman çizelgesi hazırlanmalı', 'Ekipman kontrolü: Chafing dish, servis tabakları, taşıma kapları sayılacak ve hazırlanacak'],
    templates: [{ name: 'Hasta Takip', content: '📋 Checklist: Ekipman [✓/✗] | Hammadde [✓/✗] | Personel [✓/✗] | Ulaşım [✓/✗] | İletişim: [kişi]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'Google Calendar', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Calendar', 'Google Maps', 'WhatsApp Ekip Grubu'],
    quickActions: ['Etkinlik brifingi', 'Mutfak üretim planı', 'Ekipman kontrolü'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 18,
    category: 'Otomotiv',
    name: 'Oto Servis / Tamir',
    scenarios: ['Sabah iş emri dağıtımı: 8 araç serviste, 3 motor arızası, 2 kaporta, 3 periyodik bakım', 'Yedek parça siparişi: Müşteri aracı için orijinal parça yok, muadil teklif alınmalı, müşteriye sorulmalı', 'Araç teslim: 4 araç bugün teslim edilecek, son kontrol ve test sürüşü yapılmalı'],
    templates: [{ name: 'Görev Dağılımı', content: '📱 Müşteri Bilgilendirme: [Plaka] aracınız için [işlem] tamamlandı. Tutar: [₺]. Teslim: [saat]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'Servis Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Servis Yazılımı', 'WhatsApp Business', 'Parça Katalog Sistemi'],
    quickActions: ['Sabah iş emri dağıtımı', 'Yedek parça siparişi', 'Araç teslim'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 19,
    category: 'Otomotiv',
    name: 'Oto Galeri',
    scenarios: ['Günlük stok kontrolü: Showroom\'da 35 araç, 3 yeni araç ekspertiz bekliyor, 2 araç satışa hazır', 'Müşteri takibi: Dün gelen 5 müşteri, ilgilendikleri araçlar not edildi, takip araması yapılmalı', 'İlan güncelleme: sahibinden.com ve arabam.com ilanları güncellenmeli, fiyat revizyonu yapılmalı'],
    templates: [{ name: 'Performans Özeti', content: '💰 Satış Bildirimi: [Araç] satıldı! | Alış: [₺] | Satış: [₺] | Kar: [₺] | Müşteri: [isim]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'sahibinden.com', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['sahibinden.com', 'WhatsApp', 'Araç Ekspertiz'],
    quickActions: ['Günlük stok kontrolü', 'Müşteri takibi', 'İlan güncelleme'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 20,
    category: 'Hukuk & Muhasebe',
    name: 'Avukatlık Bürosu',
    scenarios: ['Duruşma hazırlığı: Yarın 3 duruşma, dilekçeler kontrol edildi, dosya özetleri hazırlanmalı', 'Müvekkil görüşmesi: Yeni iş davası, ilk bilgi toplama görüşmesi, sözleşme incelenecek', 'Süre takibi: 2 dosyada itiraz süresi bu hafta doluyor, dilekçeler acil hazırlanmalı'],
    templates: [{ name: 'Günlük Rapor', content: '📋 Süre Uyarısı: Dosya [X] | İşlem: [itiraz/temyiz] | Son Tarih: [Y] | Kalan: [Z gün] | Aksiyon: [plan]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'UYAP', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['UYAP', 'E-İmza', 'Dosya Yönetim Sistemi'],
    quickActions: ['Duruşma hazırlığı', 'Müvekkil görüşmesi', 'Süre takibi'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 21,
    category: 'Hukuk & Muhasebe',
    name: 'Muhasebe Bürosu',
    scenarios: ['Aylık beyanname dönemi: 45 mükellefin KDV beyannamesi hazırlanacak, son gün yaklaşıyor', 'Yeni müşteri kayıt: Şirket kuruluşu yapılacak, ana sözleşme ve Ticaret Sicil işlemleri başlatılmalı', 'Vergi denetimi: Müşterinin son 3 yıl defterleri incelenecek, eksik belgeler tespit edilmeli'],
    templates: [{ name: 'Durum Güncelleme', content: '⏰ Son Tarih Hatırlatma: [Beyanname türü] son tarihi [X]. Hazırlanan: [Y/Z]. Bekleyen evrak: [liste]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'E-Beyanname', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['E-Beyanname', 'Luca/Logo Muhasebe', 'E-Defter'],
    quickActions: ['Aylık beyanname dönemi', 'Yeni müşteri kayıt', 'Vergi denetimi'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 22,
    category: 'Hukuk & Muhasebe',
    name: 'Mali Müşavirlik',
    scenarios: ['Müşteri portföy toplantısı: Aylık gelir-gider analizi, vergi planlama önerileri sunulacak', 'Teşvik başvurusu: Müşteri KOSGEB desteğine başvuracak, gerekli belge seti hazırlanmalı', 'Bordro işlemleri: 120 çalışanın bordrosu hesaplanacak, SGK bildirgeleri verilmeli'],
    templates: [{ name: 'Sabah Brifingi', content: '📄 Bordro Özeti: [Firma] | Çalışan: [X] | Brüt: [₺] | SGK: [₺] | Vergi: [₺] | Net: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'SGK E-Bildirge', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['SGK E-Bildirge', 'İŞKUR', 'KOSGEB Portal'],
    quickActions: ['Müşteri portföy toplantısı', 'Teşvik başvurusu', 'Bordro işlemleri'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 23,
    category: 'Gayrimenkul',
    name: 'Emlak Ofisi',
    scenarios: ['Günlük gösterim planı: 6 daire gösterimi, 2 yeni ilan çekimi, 1 sözleşme imzası', 'Portföy güncelleme: 3 yeni mülk eklendi, fiyat güncellemesi yapılmalı, fotoğraf çekimi planlanmalı', 'Müşteri eşleştirme: Arayan müşteri kriterleriyle portföydeki uygun mülkler eşleştirilmeli'],
    templates: [{ name: 'İlerleme Raporu', content: '💰 Fiyat Güncelleme: [İlan No] | Eski: [₺] | Yeni: [₺] | Sebep: [piyasa/müşteri talebi]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'sahibinden.com', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['sahibinden.com', 'Google Maps', 'CRM'],
    quickActions: ['Günlük gösterim planı', 'Portföy güncelleme', 'Müşteri eşleştirme'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 24,
    category: 'Güzellik & Kişisel Bakım',
    name: 'Kuaför / Güzellik Salonu',
    scenarios: ['Günlük randevu listesi: 22 randevu, 4 gelin başı, malzeme kontrolü yapılmalı', 'Personel planı: Bir çalışan rapor aldı, randevular yeniden dağıtılmalı, müşteriler bilgilendirilmeli', 'Ürün satışı: Saç bakım seti kampanyası başladı, müşterilere önerilmeli'],
    templates: [{ name: 'Kontrol Raporu', content: '✨ Kampanya: Bu hafta [ürün/hizmet] %[X] indirimli! Randevu: [telefon/link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'Randevu Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Randevu Yazılımı', 'Instagram', 'Kasa/POS'],
    quickActions: ['Günlük randevu listesi', 'Personel planı', 'Ürün satışı'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 25,
    category: 'Güzellik & Kişisel Bakım',
    name: 'Berber',
    scenarios: ['Hafta sonu yoğunluğu: Cumartesi 30+ randevu, ek personel çağrılmalı mı değerlendirilecek', 'Ürün stoku: Tıraş köpüğü ve jöle azalıyor, toptan sipariş verilmeli', 'Sadakat programı: 10 tıraşta 1 bedava kampanyası, müşteri kartları güncellenmeli'],
    templates: [{ name: 'İlk Değerlendirme', content: '🎁 Sadakat: [Müşteri] [X/10] tıraş tamamladı. [Y] tıraş sonra 1 bedava!', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'Randevu Uygulaması', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Randevu Uygulaması', 'WhatsApp', 'Kasa Sistemi'],
    quickActions: ['Hafta sonu yoğunluğu', 'Ürün stoku', 'Sadakat programı'],
    benefitScore: 7,
    teamScore: 6,
  },
  {
    id: 26,
    category: 'Üretim & Sanayi',
    name: 'Mobilya İmalathanesi',
    scenarios: ['Üretim planı: 5 mutfak dolabı, 3 gardırop siparişi, MDF ve aksesuar stok kontrolü', 'Montaj ekibi: Bugün 2 adrese montaj var, araç yükleme ve alet kontrolü yapılmalı', 'Tasarım onayı: Müşteriden renk ve aksesuar seçimi bekleniyor, üretim buna göre başlayacak'],
    templates: [{ name: 'Günlük Kayıt', content: '🚚 Montaj Bildirimi: [Müşteri], [tarih] [saat] montaj ekibimiz gelecek. Adres: [X]. Süre: ~[Y] saat', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'AutoCAD', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['AutoCAD', 'WhatsApp', 'Muhasebe Yazılımı'],
    quickActions: ['Üretim planı', 'Montaj ekibi', 'Tasarım onayı'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 27,
    category: 'Üretim & Sanayi',
    name: 'Matbaa / Baskı',
    scenarios: ['Günlük iş listesi: 3 kartvizit, 2 katalog, 1 afiş baskısı, kağıt stok kontrolü', 'Renk prova: Müşteriye baskı öncesi renk provası gönderilecek, onay alınmalı', 'Makine bakımı: Dijital baskı makinesinin haftalık bakım zamanı, üretim planı buna göre ayarlanmalı'],
    templates: [{ name: 'Vardiya Raporu', content: '✅ Prova Onayı: [Müşteri], baskı provanız hazır. Onayınız sonrası üretime geçilecek. Termin: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'Adobe Creative Suite', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Adobe Creative Suite', 'WeTransfer/Drive', 'Kasa'],
    quickActions: ['Günlük iş listesi', 'Renk prova', 'Makine bakımı'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 28,
    category: 'Üretim & Sanayi',
    name: 'Tekstil Atölyesi',
    scenarios: ['Sipariş takibi: 500 adet t-shirt siparişi, kumaş kesimi tamamlandı, dikime geçilecek', 'Kalite kontrol: İlk parti 50 adet kontrol edilecek, ölçü ve dikiş kalitesi değerlendirilmeli', 'Kumaş tedariki: Yeni sezon için kumaş numuneleri geldi, müşteriyle değerlendirilecek'],
    templates: [{ name: 'İş Emri', content: '🧵 Numune Onayı: [Müşteri], [ürün] numunesi hazır. Fotoğraflar ekte. Onayınız bekleniyor', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'ERP Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['ERP Sistemi', 'WhatsApp', 'Kargo Entegrasyonu'],
    quickActions: ['Sipariş takibi', 'Kalite kontrol', 'Kumaş tedariki'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 29,
    category: 'Lojistik & Ulaşım',
    name: 'Kargo / Kurye Firması',
    scenarios: ['Sabah dağıtım planı: 85 paket, 3 bölgeye ayrılacak, rotalar optimize edilmeli', 'Sorunlu teslimat: 5 pakette adres problemi var, müşterilerle iletişim kurulmalı', 'Araç bakımı: 2 aracın sigorta yenileme zamanı, 1 aracın periyodik bakımı yapılmalı'],
    templates: [{ name: 'Seans Notu', content: '❌ Teslimat Sorunu: [Takip No] | Sorun: [adres/müşteri yok/hasarlı] | Aksiyon: [yeniden dene/iade]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'Rota Optimizasyonu', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Rota Optimizasyonu', 'SMS Gateway', 'Barkod/QR Sistemi'],
    quickActions: ['Sabah dağıtım planı', 'Sorunlu teslimat', 'Araç bakımı'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 30,
    category: 'Lojistik & Ulaşım',
    name: 'Nakliye Firması',
    scenarios: ['Günlük sefer planı: 3 şehirlerarası taşıma, TIR yükleme sırası ve rota planlaması', 'Gümrük işlemleri: İhracat yükü için gümrük evrakları hazırlanacak, müşteri bilgilendirilecek', 'Şoför takibi: Takograf verileri kontrol edilmeli, dinlenme süreleri yasaya uygun mu?'],
    templates: [{ name: 'Stok Uyarısı', content: '📋 Gümrük Durumu: [Yük] | CMR: [var/yok] | Fatura: [hazır/bekliyor] | Beyanname: [durum]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'GPS Takip', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['GPS Takip', 'Gümrük Yazılımı', 'ERP'],
    quickActions: ['Günlük sefer planı', 'Gümrük işlemleri', 'Şoför takibi'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 31,
    category: 'Turizm & Konaklama',
    name: 'Otel / Pansiyon',
    scenarios: ['Sabah brifingi: Bugün 12 check-in, 8 check-out, oda hazırlık durumu kontrol edilmeli', 'Misafir şikayeti: Klima arızası bildirimi, teknik ekip yönlendirilmeli, misafir telafi edilmeli', 'Kanal yönetimi: Booking.com, Airbnb fiyatları güncellenmeli, hafta sonu için minimum konaklama ayarlanmalı'],
    templates: [{ name: 'Üretim Raporu', content: '⭐ Geri Bildirim: [Misafir], konaklamanız nasıldı? Değerlendirmeniz bizim için önemli: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Booking.com/Airbnb', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Booking.com/Airbnb', 'PMS (Otel Yazılımı)', 'Online Ödeme'],
    quickActions: ['Sabah brifingi', 'Misafir şikayeti', 'Kanal yönetimi'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 32,
    category: 'Turizm & Konaklama',
    name: 'Tur Operatörü / Seyahat Acentesi',
    scenarios: ['Tur hazırlığı: Yarınki Kapadokya turu, 35 kişi, otobüs ve rehber teyidi alınmalı', 'Müşteri talebi: Balayı paketi hazırlanacak, otel + uçak + transfer fiyatlandırma yapılmalı', 'Tedarikçi mutabakat: Otel ve transfer firmasıyla aylık hesap mutabakatı yapılmalı'],
    templates: [{ name: 'Çekim Brifingi', content: '🌴 Paket Teklif: [Müşteri] | Destinasyon: [X] | Tarih: [Y-Z] | Kişi: [N] | Fiyat: [₺] | Dahil: [liste]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'GDS Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['GDS Sistemi', 'WhatsApp', 'Muhasebe'],
    quickActions: ['Tur hazırlığı', 'Müşteri talebi', 'Tedarikçi mutabakat'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 33,
    category: 'Tarım & Hayvancılık',
    name: 'Sera İşletmesi',
    scenarios: ['Sabah kontrol: Sera sıcaklık ve nem verileri okundu, havalandırma otomasyonu kontrol edilmeli', 'Hasat planı: Domates hasadı başlayacak, işçi ekibi organize edilmeli, kasa ve paketleme hazırlanmalı', 'Bitki sağlığı: 3. bölümde yaprak kıvrılması tespit edildi, ilaçlama programı başlatılmalı'],
    templates: [{ name: 'Proje Durumu', content: '🍅 Hasat Raporu: Tarih [X] | Ürün: [Y] | Miktar: [kg] | Kalite: [1/2/3 sınıf] | Sevkiyat: [alıcı]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'IoT Sensörler', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['IoT Sensörler', 'WhatsApp', 'Hal Kayıt Sistemi'],
    quickActions: ['Sabah kontrol', 'Hasat planı', 'Bitki sağlığı'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 34,
    category: 'Tarım & Hayvancılık',
    name: 'Çiftlik / Hayvancılık',
    scenarios: ['Sabah bakım: Hayvan sağlık kontrolü, yem dağıtımı, süt sağım verileri kaydedilmeli', 'Veteriner ziyareti: Aşı programı kapsamında sürü aşılaması planlanmalı, küpe kontrolü yapılmalı', 'Yem stoku: 1 haftalık yem kaldı, tedarikçiye sipariş verilmeli, fiyat karşılaştırması yapılmalı'],
    templates: [{ name: 'Hizmet Raporu', content: '💉 Aşı Takibi: Tarih [X] | Aşı: [tür] | Uygulanan: [Y baş] | Kalan: [Z baş] | Veteriner: [isim]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'Sürü Takip Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Sürü Takip Yazılımı', 'Devlet Destekleri Portal', 'WhatsApp'],
    quickActions: ['Sabah bakım', 'Veteriner ziyareti', 'Yem stoku'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 35,
    category: 'Spor & Fitness',
    name: 'Spor Salonu / Fitness',
    scenarios: ['Açılış kontrolü: Cihazlar kontrol edildi, havuz pH ölçümü yapıldı, temizlik tamamlandı', 'Üyelik takibi: 15 üyelik bu ay sona eriyor, yenileme kampanyası ile iletişime geçilmeli', 'Grup dersleri: Bu hafta yoga ve pilates eğitmeni değişti, üyelere bildirim gönderilmeli'],
    templates: [{ name: 'Etkinlik Brifingi', content: '📅 Ders Değişikliği: [Ders] [tarih] [eski saat] yerine [yeni saat]\'te. Eğitmen: [yeni isim]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'Üyelik Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Üyelik Yazılımı', 'Push Bildirim', 'Turnike Sistemi'],
    quickActions: ['Açılış kontrolü', 'Üyelik takibi', 'Grup dersleri'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 36,
    category: 'Spor & Fitness',
    name: 'Halı Saha / Spor Tesisi',
    scenarios: ['Günlük saha programı: 3 saha, 12 saat rezervasyon dolu, boş saatler için kampanya yapılmalı', 'Saha bakımı: 1 numaralı sahanın çimi yıpranmış, bakım planlanmalı, o sahanın rezervasyonları ayarlanmalı', 'Turnuva organizasyonu: Hafta sonu turnuva, 16 takım, fikstür ve hakem ataması yapılmalı'],
    templates: [{ name: 'Sipariş Takip', content: '🏆 Turnuva Duyurusu: [Turnuva adı] | Tarih: [X] | Format: [Y] | Son Kayıt: [Z] | Ücret: [₺/takım]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Rezervasyon Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Rezervasyon Sistemi', 'WhatsApp Grupları', 'Online Ödeme'],
    quickActions: ['Günlük saha programı', 'Saha bakımı', 'Turnuva organizasyonu'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 37,
    category: 'Temizlik & Hizmet',
    name: 'Temizlik Şirketi',
    scenarios: ['Günlük ekip dağılımı: 4 ekip, 12 lokasyon, malzeme kontrolü ve araç yükleme', 'Müşteri şikayeti: Dün yapılan ofis temizliğinden memnuniyetsizlik, yeniden gönderim planlanmalı', 'Yeni sözleşme: Alışveriş merkezi haftalık temizlik teklifi hazırlanacak'],
    templates: [{ name: 'Hasta Takip', content: '✅ İş Tamamlama: [Müşteri], [tarih] temizlik tamamlandı. Kontrol notu: [puan]. Sonraki: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'Google Maps/Rota', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Maps/Rota', 'WhatsApp Ekip', 'Müşteri Takip CRM'],
    quickActions: ['Günlük ekip dağılımı', 'Müşteri şikayeti', 'Yeni sözleşme'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 38,
    category: 'Temizlik & Hizmet',
    name: 'Kuru Temizleme',
    scenarios: ['Sabah teslim alım: Gece bırakılan 15 parça etiketlenecek, leke kontrolü yapılacak', 'Teslim bildirimi: Hazır olan 20 parça için müşterilere bildirim gönderilmeli', 'Makine bakımı: Ütü presinin basınç ayarı yapılmalı, teknisyen çağrılacak'],
    templates: [{ name: 'Görev Dağılımı', content: '📋 Alım Fişi: Fiş [No] | Parça: [X adet] | Tür: [detay] | Özel Not: [leke/hasar] | Teslim: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'Otomasyon Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Otomasyon Yazılımı', 'SMS', 'Barkod Sistemi'],
    quickActions: ['Sabah teslim alım', 'Teslim bildirimi', 'Makine bakımı'],
    benefitScore: 6,
    teamScore: 5,
  },
  {
    id: 39,
    category: 'Medya & Yaratıcı',
    name: 'Fotoğraf / Video Prodüksiyon',
    scenarios: ['Çekim günü: Düğün çekimi, 2 kameraman + 1 drone, ekipman kontrolü ve şarj durumu', 'Post-prodüksiyon: 3 düğünün kurgusu bekliyor, teslim tarihleri yaklaşıyor, iş dağılımı yapılmalı', 'Müşteri sunum: Nişan çekimi fotoğrafları seçildi, online galeri hazırlanacak'],
    templates: [{ name: 'Performans Özeti', content: '🎬 Teslim Bildirimi: [Müşteri], [etkinlik] fotoğraf/video çalışmanız hazır. Galeri: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'Google Drive/Dropbox', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Drive/Dropbox', 'Pixieset/Galeri', 'Adobe Premiere/Lightroom'],
    quickActions: ['Çekim günü', 'Post-prodüksiyon', 'Müşteri sunum'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 40,
    category: 'Medya & Yaratıcı',
    name: 'Grafik Tasarım Stüdyosu',
    scenarios: ['Günlük iş listesi: 3 logo tasarımı, 2 ambalaj tasarımı, 1 kurumsal kimlik projesi devam ediyor', 'Müşteri feedback: Logo revizyonu geldi, 3. konsept üzerinde devam edilecek, renk değişikliği isteniyor', 'Font lisans kontrolü: Projede kullanılan fontların ticari lisansları kontrol edilmeli'],
    templates: [{ name: 'Günlük Rapor', content: '✅ Tasarım Teslim: [Müşteri], [proje] tasarımınız onayınıza sunulmuştur. Link: [X]. Son Onay: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'Figma/Adobe CC', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Figma/Adobe CC', 'WeTransfer', 'Proje Yönetim Aracı'],
    quickActions: ['Günlük iş listesi', 'Müşteri feedback', 'Font lisans kontrolü'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 41,
    category: 'Medya & Yaratıcı',
    name: 'Sosyal Medya Yönetimi',
    scenarios: ['Günlük paylaşım kontrolü: 5 müşteri için bugünkü içerikler hazır mı, zamanlama doğru mu', 'Kriz yönetimi: Müşterinin markasına olumsuz yorum seli, yanıt stratejisi belirlenecek', 'İçerik üretimi: Bu hafta için reels/TikTok fikirleri briefingi, çekim planı yapılmalı'],
    templates: [{ name: 'Durum Güncelleme', content: '🚨 Kriz Yanıt: [Müşteri] | Sorun: [özet] | Yanıt Stratejisi: [kabul/açıklama/yönlendirme] | Onay: [kişi]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Buffer/Hootsuite', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Buffer/Hootsuite', 'Canva', 'Meta Business Suite'],
    quickActions: ['Günlük paylaşım kontrolü', 'Kriz yönetimi', 'İçerik üretimi'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 42,
    category: 'Enerji & Teknik',
    name: 'Elektrik Tesisat',
    scenarios: ['Günlük görev: 3 yeni daire tesisatı, 2 arıza tamiri, malzeme listesi hazırlanacak', 'Proje teklifi: Fabrika aydınlatma projesi için keşif yapılacak, teklif hazırlanmalı', 'Güvenlik kontrolü: Topraklama ölçümleri yapılacak, rapor düzenlenecek'],
    templates: [{ name: 'Sabah Brifingi', content: '📋 Teklif: [Müşteri] | Proje: [detay] | Malzeme: [₺] | İşçilik: [₺] | Toplam: [₺] | Geçerlilik: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'Google Maps', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Maps', 'WhatsApp', 'Muhasebe'],
    quickActions: ['Günlük görev', 'Proje teklifi', 'Güvenlik kontrolü'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 43,
    category: 'Enerji & Teknik',
    name: 'Tesisat (Su/Doğalgaz)',
    scenarios: ['Acil çağrılar: 2 su tesisatı arızası, 1 doğalgaz kaçak kontrolü, öncelik sıralaması yapılmalı', 'Proje işi: Yeni bina tesisatı, kat planına göre boru hattı çizimi ve malzeme hesabı', 'Periyodik bakım: 10 dairenin kombi bakımı planlanmalı, randevular verilmeli'],
    templates: [{ name: 'İlerleme Raporu', content: '🔥 Kombi Bakım: Sayın [isim], yıllık kombi bakım zamanınız geldi. Randevu: [tarih seçenekleri]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'Google Calendar', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Calendar', 'WhatsApp', 'Fatura/Muhasebe'],
    quickActions: ['Acil çağrılar', 'Proje işi', 'Periyodik bakım'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 44,
    category: 'Enerji & Teknik',
    name: 'Güneş Enerjisi (Solar)',
    scenarios: ['Proje keşif: 3 çatı keşfi planlandı, uydu görüntüsü incelendi, ölçüm yapılacak', 'Kurulum takibi: 10 kW panel kurulumu devam ediyor, invertör bağlantısı bugün yapılacak', 'Performans izleme: Mevcut müşterilerin üretim verileri kontrol edilmeli, düşük üretim olanlar tespit edilmeli'],
    templates: [{ name: 'Kontrol Raporu', content: '📊 Üretim Raporu: [Müşteri] | Bu Ay: [kWh] | Beklenen: [kWh] | Performans: [%] | Kazanç: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'İzleme Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['İzleme Yazılımı', 'Google Earth', 'E-Devlet/EDAŞ'],
    quickActions: ['Proje keşif', 'Kurulum takibi', 'Performans izleme'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 45,
    category: 'Finans & Sigorta',
    name: 'Sigorta Acentesi',
    scenarios: ['Vadesi dolan poliçeler: Bu hafta 25 poliçe yenilenecek, müşterilerle iletişim başlatılmalı', 'Hasar dosyası: Müşterinin trafik kazası hasarı, dosya açılacak, eksper randevusu alınmalı', 'Yeni müşteri teklifi: Konut + DASK + kasko teklifi hazırlanacak, en uygun paket sunulmalı'],
    templates: [{ name: 'İlk Değerlendirme', content: '📋 Hasar Takip: Dosya [X] | Tür: [kasko/trafik/konut] | Durum: [açık/eksper/ödeme] | Tutar: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'Sigorta Şirketi Portalı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Sigorta Şirketi Portalı', 'SMS', 'CRM'],
    quickActions: ['Vadesi dolan poliçeler', 'Hasar dosyası', 'Yeni müşteri teklifi'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 46,
    category: 'Finans & Sigorta',
    name: 'Finansal Danışmanlık',
    scenarios: ['Müşteri portföy revizyonu: Piyasa hareketlerine göre 5 müşterinin yatırım dağılımı gözden geçirilmeli', 'Vergi planlama: Yıl sonu yaklaşıyor, müşterilerin vergi avantajı fırsatları değerlendirilmeli', 'Yeni müşteri onboarding: Risk profili analizi yapılacak, yatırım stratejisi oluşturulacak'],
    templates: [{ name: 'Günlük Kayıt', content: '📊 Piyasa Bülteni: [Tarih] | BIST: [değer] | Dolar: [₺] | Euro: [₺] | Altın: [₺] | Yorum: [özet]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Borsa Platformu', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Borsa Platformu', 'Bloomberg/Matriks', 'CRM'],
    quickActions: ['Müşteri portföy revizyonu', 'Vergi planlama', 'Yeni müşteri onboarding'],
    benefitScore: 7,
    teamScore: 6,
  },
  {
    id: 47,
    category: 'Perakende',
    name: 'Mağaza (Giyim/Ayakkabı)',
    scenarios: ['Sabah açılış: Vitrin düzeni kontrol, kasa sayımı, yeni gelen ürünler reyona yerleştirilmeli', 'Satış hedefi takibi: Aylık hedefin %65\'i tamamlandı, kampanya planlanmalı', 'İade işlemi: Müşteri değişim/iade istiyor, ürün kontrolü ve süreç yönetimi'],
    templates: [{ name: 'Vardiya Raporu', content: '🔖 Kampanya: [Ürün grubu] %[X] indirim! [Tarih aralığı]. Mağaza + online geçerli', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'POS Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['POS Sistemi', 'Instagram/TikTok', 'E-ticaret Entegrasyonu'],
    quickActions: ['Sabah açılış', 'Satış hedefi takibi', 'İade işlemi'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 48,
    category: 'Perakende',
    name: 'Market / Bakkal',
    scenarios: ['Sabah teslimat: Ekmek, süt ve günlük ürünler geldi, raf düzeni yapılacak, SKT kontrol', 'Stok sayımı: Haftalık sayım günü, eksik ürünler tespit edilip sipariş verilecek', 'Fiyat güncelleme: Tedarikçi zam bildirdi, etiketler güncellenmeli'],
    templates: [{ name: 'İş Emri', content: '💰 Fiyat Güncelleme: [Ürün listesi] | Eski: [₺] | Yeni: [₺] | Geçerlilik: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'Kasa/Barkod', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Kasa/Barkod', 'Tedarikçi WhatsApp', 'Muhasebe'],
    quickActions: ['Sabah teslimat', 'Stok sayımı', 'Fiyat güncelleme'],
    benefitScore: 6,
    teamScore: 5,
  },
  {
    id: 49,
    category: 'Danışmanlık',
    name: 'İş / Yönetim Danışmanlığı',
    scenarios: ['Müşteri workshop: Strateji çalıştayı hazırlığı, sunum ve materyaller kontrol edilmeli', 'Proje raporu: Aylık ilerleme raporu hazırlanacak, KPI\'lar analiz edilmeli', 'Yeni proje teklifi: Kurumsal dönüşüm projesi için scope ve fiyatlama hazırlanacak'],
    templates: [{ name: 'Seans Notu', content: '📋 Workshop Daveti: [Konu] | Tarih: [X] | Saat: [Y-Z] | Yer: [adres/online] | Hazırlık: [ön okuma]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'PowerPoint/Canva', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['PowerPoint/Canva', 'Zoom/Teams', 'CRM'],
    quickActions: ['Müşteri workshop', 'Proje raporu', 'Yeni proje teklifi'],
    benefitScore: 9,
    teamScore: 8,
  },
  {
    id: 50,
    category: 'Danışmanlık',
    name: 'İnsan Kaynakları Danışmanlığı',
    scenarios: ['İşe alım süreci: 3 pozisyon için mülakat planlanmalı, aday havuzu gözden geçirilmeli', 'Bordro danışmanlığı: Müşteri firmanın SGK bildirgeleri kontrol edilecek, uyumsuzluklar raporlanmalı', 'Eğitim programı: Liderlik eğitimi içeriği hazırlanacak, katılımcı listesi kesinleştirilmeli'],
    templates: [{ name: 'Stok Uyarısı', content: '📧 Mülakat Daveti: Sayın [isim], [pozisyon] için [tarih] [saat] görüşme. Yer: [adres/link]. İletişim: [kişi]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'LinkedIn', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['LinkedIn', 'ATS Yazılımı', 'Zoom/Teams'],
    quickActions: ['İşe alım süreci', 'Bordro danışmanlığı', 'Eğitim programı'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 51,
    category: 'Sanat & Eğlence',
    name: 'Müzik / Dans Okulu',
    scenarios: ['Günlük ders programı: 8 bireysel, 4 grup dersi, stüdyo kullanım çizelgesi kontrol edilmeli', 'Konser hazırlığı: Yılsonu konseri 2 hafta sonra, prova takvimi ve mekan organizasyonu', 'Yeni öğrenci kaydı: Deneme dersi planlanacak, seviye değerlendirmesi yapılacak'],
    templates: [{ name: 'Üretim Raporu', content: '🎶 Konser Duyurusu: [Etkinlik] | Tarih: [X] | Saat: [Y] | Yer: [Z] | Bilet/Davetiye: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Google Calendar', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Calendar', 'Instagram', 'Online Ödeme'],
    quickActions: ['Günlük ders programı', 'Konser hazırlığı', 'Yeni öğrenci kaydı'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 52,
    category: 'Sanat & Eğlence',
    name: 'Etkinlik / Organizasyon',
    scenarios: ['Etkinlik brifingi: Hafta sonu düğün organizasyonu, tüm tedarikçilerle son teyitler alınmalı', 'Mekan kontrolü: Etkinlik alanı yerleşim planı, ses-ışık testi, dekorasyon ekibi koordinasyonu', 'Bütçe takibi: Müşteri bütçe aşımı riski var, alternatif çözümler sunulmalı'],
    templates: [{ name: 'Çekim Brifingi', content: '📞 Tedarikçi Teyit: [Tedarikçi] | Hizmet: [detay] | Tarih: [X] | Saat: [Y] | Adres: [Z] | Teyit: [evet/hayır]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'Google Sheets', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Sheets', 'WhatsApp', 'Pinterest/Canva'],
    quickActions: ['Etkinlik brifingi', 'Mekan kontrolü', 'Bütçe takibi'],
    benefitScore: 9,
    teamScore: 9,
  },
  {
    id: 53,
    category: 'Teknik Servis',
    name: 'Beyaz Eşya / Klima Servisi',
    scenarios: ['Günlük servis planı: 8 ev ziyareti, 3 klima bakımı, 5 beyaz eşya tamiri, yedek parça kontrolü', 'Garanti kontrolü: Müşterinin bulaşık makinesi garanti kapsamında mı, seri numarası kontrol edilmeli', 'Mevsimsel yoğunluk: Klima sezonu başlıyor, ek teknisyen alınmalı mı değerlendirilecek'],
    templates: [{ name: 'Proje Durumu', content: '📞 Randevu: Sayın [isim], [cihaz] servisiniz [tarih] [saat aralığı]. Teknisyen: [isim]. Adres teyidi: [onay link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'Servis Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Servis Yazılımı', 'Google Maps/Rota', 'Yedek Parça Kataloğu'],
    quickActions: ['Günlük servis planı', 'Garanti kontrolü', 'Mevsimsel yoğunluk'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 54,
    category: 'Teknik Servis',
    name: 'Asansör Bakım',
    scenarios: ['Periyodik bakım planı: Bu hafta 20 bina bakımı, bakım kartları ve ekipman hazırlanmalı', 'Arıza çağrısı: Asansör kapı arızası, acil müdahale ekibi yönlendirilmeli', 'Yıllık kontrol: 5 asansörün TSE kontrolü yaklaşıyor, evrak hazırlığı başlatılmalı'],
    templates: [{ name: 'Hizmet Raporu', content: '🚨 Arıza Bildirimi: Bina [X] | Asansör: [kat/numara] | Arıza: [detay] | Tahmini Süre: [saat] | Teknisyen: [isim]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'Bakım Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Bakım Yazılımı', 'WhatsApp Arıza Hattı', 'TSE Portal'],
    quickActions: ['Periyodik bakım planı', 'Arıza çağrısı', 'Yıllık kontrol'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 55,
    category: 'Profesyonel Hizmetler',
    name: 'Tercüme Bürosu',
    scenarios: ['Günlük iş dağılımı: 5 belge tercümesi, 2 simultane tercüme randevusu, deadline kontrolü', 'Kalite kontrol: Tamamlanan hukuki tercüme, uzman redaktör tarafından kontrol edilmeli', 'Yeni proje: 200 sayfalık teknik kılavuz tercümesi, ekip ve timeline planlaması yapılmalı'],
    templates: [{ name: 'Etkinlik Brifingi', content: '📋 Teklif: [Müşteri] | Belge: [tür] | Hacim: [kelime/sayfa] | Dil: [çift] | Tutar: [₺] | Süre: [gün]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'CAT Tools (SDL/MemoQ)', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['CAT Tools (SDL/MemoQ)', 'E-posta', 'Fatura Sistemi'],
    quickActions: ['Günlük iş dağılımı', 'Kalite kontrol', 'Yeni proje'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 56,
    category: 'Profesyonel Hizmetler',
    name: 'Güvenlik Şirketi',
    scenarios: ['Vardiya değişimi: Gece-gündüz vardiya devir teslimi, önemli olaylar aktarılmalı', 'Personel planı: 3 yeni site başlıyor, güvenlik görevlisi ataması yapılmalı', 'Olay raporu: Gece nöbetinde şüpheli kişi tespit edildi, kamera kayıtları ve rapor hazırlanmalı'],
    templates: [{ name: 'Sipariş Takip', content: '⚠️ Olay Raporu: Site [X] | Zaman: [saat] | Olay: [detay] | Müdahale: [yapılan] | Durum: [sonuç]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Güvenlik Kamera Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Güvenlik Kamera Sistemi', 'Telsiz/WhatsApp', 'Vardiya Yazılımı'],
    quickActions: ['Vardiya değişimi', 'Personel planı', 'Olay raporu'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 57,
    category: 'Profesyonel Hizmetler',
    name: 'Reklam Ajansı',
    scenarios: ['Kreatif briefingi: Yeni müşteri kampanyası, strateji ve konsept toplantısı yapılacak', 'Sunum hazırlığı: Müşteriye kampanya sunumu yarın, tasarımlar ve medya planı tamamlanmalı', 'Medya satın alma: TV ve dijital reklam bütçeleri onaylandı, satın alma emirleri verilecek'],
    templates: [{ name: 'Hasta Takip', content: '📊 Kampanya Raporu: [Müşteri] | Erişim: [X] | Etkileşim: [Y] | Dönüşüm: [Z] | Harcama: [₺] | ROI: [%]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'Google Ads/Meta', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Google Ads/Meta', 'Adobe CC', 'Medya Ajansı Portal'],
    quickActions: ['Kreatif briefingi', 'Sunum hazırlığı', 'Medya satın alma'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 58,
    category: 'Otomotiv Hizmet',
    name: 'Oto Yıkama',
    scenarios: ['Sabah hazırlık: Su deposu ve kimyasal stok kontrolü, makine çalışma testi', 'Müşteri sırası: 15 araç sırada, VIP müşteri öncellenmeli, tahmini süre bildirilmeli', 'Abonelik kampanyası: Aylık 4 yıkama paketi kampanyası başlatılacak'],
    templates: [{ name: 'Görev Dağılımı', content: '💳 Abonelik: [Müşteri] | Paket: [aylık X yıkama] | Tutar: [₺/ay] | Başlangıç: [tarih]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'Kasa Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Kasa Sistemi', 'WhatsApp', 'SMS'],
    quickActions: ['Sabah hazırlık', 'Müşteri sırası', 'Abonelik kampanyası'],
    benefitScore: 6,
    teamScore: 5,
  },
  {
    id: 59,
    category: 'Otomotiv Hizmet',
    name: 'Lastik / Rot Balans',
    scenarios: ['Sezon değişimi yoğunluğu: Kış lastiği sezonunda günlük 30+ araç, ek personel ve stok planlaması', 'Stok durumu: Popüler ebatlarda stok azalıyor, distribütörden acil sipariş verilmeli', 'Müşteri hatırlatma: Geçen sezon lastik bırakanları arayıp değişim randevusu verilmeli'],
    templates: [{ name: 'Performans Özeti', content: '📞 Sezon Hatırlatma: [Müşteri], kış/yaz lastiği değişim zamanı! Depodaki lastikleriniz: [detay]. Randevu: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'Stok Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Stok Yazılımı', 'SMS/WhatsApp', 'Randevu Sistemi'],
    quickActions: ['Sezon değişimi yoğunluğu', 'Stok durumu', 'Müşteri hatırlatma'],
    benefitScore: 7,
    teamScore: 6,
  },
  {
    id: 60,
    category: 'Sağlık',
    name: 'Optik / Gözlükçü',
    scenarios: ['Günlük randevu: 10 göz muayenesi, 5 lens uyumu, 3 gözlük teslim', 'Sipariş takibi: 8 cam siparişi laboratuvarda, teslim tarihleri kontrol edilmeli', 'Kampanya: Çerçevede 2. ürün %50 indirim kampanyası başlatılacak, vitrin düzenlenecek'],
    templates: [{ name: 'Günlük Rapor', content: '👁️ Kontrol Hatırlatma: Sayın [isim], yıllık göz kontrolünüz için randevu zamanı geldi. Randevu: [link]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'Optik Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Optik Yazılımı', 'SMS', 'Cam Laboratuvarı'],
    quickActions: ['Günlük randevu', 'Sipariş takibi', 'Kampanya'],
    benefitScore: 7,
    teamScore: 6,
  },
  {
    id: 61,
    category: 'Lojistik & Ulaşım',
    name: 'Araç Kiralama',
    scenarios: ['Sabah kontrol: Dönen araçlar hasar kontrolü, temizlik, yakıt durumu kontrol edilmeli', 'Rezervasyon yönetimi: Bugün 5 teslimat, 3 iade, araç hazırlık durumu takip edilmeli', 'Fiyat güncelleme: Hafta sonu ve tatil dönemi fiyatları ayarlanmalı'],
    templates: [{ name: 'Durum Güncelleme', content: '📋 İade Kontrol: Araç [plaka] | Km: [X] | Yakıt: [%] | Hasar: [var/yok] | Ek Ücret: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Randevu Hatırlatma', content: 'Filo Yönetim Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Filo Yönetim Yazılımı', 'Online Rezervasyon', 'Sigorta Sistemi'],
    quickActions: ['Sabah kontrol', 'Rezervasyon yönetimi', 'Fiyat güncelleme'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 62,
    category: 'İnsan Kaynakları',
    name: 'İşe Alım / Headhunting',
    scenarios: ['Günlük aday taraması: 5 aktif pozisyon için LinkedIn ve iş ilanlarından aday havuzu oluşturulacak', 'Mülakat koordinasyonu: 8 mülakat planlanacak, müşteri firma yöneticileriyle takvim eşleştirilmeli', 'Referans kontrolü: 2 final adayın referansları aranacak, rapor hazırlanacak'],
    templates: [{ name: 'Sabah Brifingi', content: '📧 Mülakat Daveti: Sayın [isim], [şirket] [pozisyon] görüşmesi [tarih] [saat]. Format: [yüz yüze/online]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Kampanya Duyurusu', content: 'LinkedIn Recruiter', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['LinkedIn Recruiter', 'ATS', 'Zoom/Teams'],
    quickActions: ['Günlük aday taraması', 'Mülakat koordinasyonu', 'Referans kontrolü'],
    benefitScore: 8,
    teamScore: 7,
  },
  {
    id: 63,
    category: 'Sağlık',
    name: 'Diyetisyen / Beslenme Danışmanı',
    scenarios: ['Günlük randevular: 8 danışan, 3 ilk görüşme (ölçüm + anamnez), 5 takip seansı', 'Diyet programı hazırlığı: 4 kişiselleştirilmiş beslenme planı yazılacak, alışveriş listeleri oluşturulacak', 'Takip analizi: Haftalık ölçüm karşılaştırmaları yapılacak, hedef değerlendirmesi'],
    templates: [{ name: 'İlerleme Raporu', content: '📋 Randevu Hatırlatma: Sayın [isim], [tarih] [saat] kontrol randevunuz var. Ölçümlerinizi getirmeyi unutmayın', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teslim Bildirimi', content: 'Danışan Takip Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Danışan Takip Yazılımı', 'WhatsApp', 'Vücut Analiz Cihazı'],
    quickActions: ['Günlük randevular', 'Diyet programı hazırlığı', 'Takip analizi'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 64,
    category: 'İnşaat & Mimarlık',
    name: 'İç Mimarlık / Dekorasyon',
    scenarios: ['Proje takibi: 3 aktif proje, mobilya siparişleri kontrol edilmeli, termin takibi yapılmalı', 'Müşteri sunumu: Yeni salon tasarımı render\'ları hazır, sunum dosyası oluşturulmalı', 'Fuar ziyareti: Mobilya fuarında yeni trendler ve tedarikçi ilişkileri geliştirilecek'],
    templates: [{ name: 'Kontrol Raporu', content: '🛋️ Mobilya Takip: [Müşteri] | Ürün: [detay] | Tedarikçi: [X] | Sipariş: [tarih] | Teslim: [tahmini]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Hatırlatma Mesajı', content: 'SketchUp/3ds Max', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['SketchUp/3ds Max', 'Pinterest/Instagram', 'Tedarikçi Portal'],
    quickActions: ['Proje takibi', 'Müşteri sunumu', 'Fuar ziyareti'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 65,
    category: 'Sağlık',
    name: 'Psikolojik Danışmanlık',
    scenarios: ['Günlük seans programı: 6 bireysel seans, 1 çift terapisi, seans notları hazırlanmalı', 'Kriz müdahalesi: Acil danışan başvurusu, programa ekstra seans sıkıştırılmalı', 'Süpervizyon: Haftalık vaka tartışması, seçilen vakaların süpervizöre sunumu hazırlanmalı'],
    templates: [{ name: 'İlk Değerlendirme', content: '📝 Süpervizyon Notu: Vaka [X] | Seans: [Y.] | Tema: [ana konu] | Müdahale: [yöntem] | Sonraki: [plan]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Teklif Gönderimi', content: 'Online Terapi Platformu', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Online Terapi Platformu', 'Randevu Yazılımı', 'Güvenli Arşiv'],
    quickActions: ['Günlük seans programı', 'Kriz müdahalesi', 'Süpervizyon'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 66,
    category: 'Perakende',
    name: 'Pet Shop',
    scenarios: ['Sabah bakım: Satılık hayvanlar beslendi, su değiştirildi, kafes temizliği yapıldı', 'Stok kontrolü: Mama ve aksesuar stoku kontrol edilmeli, popüler ürünler yeniden sipariş verilmeli', 'Veteriner günü: Haftalık veteriner kontrol günü, satılık hayvanların sağlık kontrolü'],
    templates: [{ name: 'Günlük Kayıt', content: '🐾 Kampanya: [Ürün grubu] %[X] indirimli! [Tarih aralığı]. Sadakat kartı sahiplerine ekstra [Y]%', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Onay Talebi', content: 'Kasa/Barkod', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Kasa/Barkod', 'Instagram', 'Tedarikçi Sipariş'],
    quickActions: ['Sabah bakım', 'Stok kontrolü', 'Veteriner günü'],
    benefitScore: 6,
    teamScore: 6,
  },
  {
    id: 67,
    category: 'Eğitim',
    name: 'Online Eğitim Platformu',
    scenarios: ['İçerik üretimi: 3 yeni ders videosu çekilecek, senaryo ve sunum hazırlanmalı', 'Öğrenci destek: 25 destek talebi cevaplanacak, sık sorulan sorular güncellenmeli', 'Platform analizi: Kurs tamamlama oranları düşük, video süreleri ve içerik analiz edilmeli'],
    templates: [{ name: 'Vardiya Raporu', content: '📊 Haftalık Rapor: Yeni Kayıt: [X] | Aktif: [Y] | Tamamlama: [%] | Memnuniyet: [puan] | Gelir: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Şikayet Yanıtı', content: 'LMS Platformu', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['LMS Platformu', 'Zoom/OBS', 'Ödeme Sistemi'],
    quickActions: ['İçerik üretimi', 'Öğrenci destek', 'Platform analizi'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 68,
    category: 'Gıda & Restoran',
    name: 'Gıda Üretimi / Paketleme',
    scenarios: ['Üretim hattı kontrolü: Makine kalibrasyonları yapıldı, hammadde kalite kontrolü tamamlandı', 'Sevkiyat planı: Bugün 5 müşteriye sevkiyat, araç yükleme sırası ve irsaliye hazırlığı', 'HACCP kontrolü: Kritik kontrol noktaları denetimi, sıcaklık kayıtları ve temizlik kontrolleri'],
    templates: [{ name: 'İş Emri', content: '📦 Sevkiyat: [Müşteri] | Ürün: [liste] | Miktar: [adet/kg] | Araç: [plaka] | Çıkış: [saat] | İrsaliye: [no]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Fiyat Bildirimi', content: 'ERP Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['ERP Sistemi', 'Sıcaklık İzleme', 'Barkod/Lot Takip'],
    quickActions: ['Üretim hattı kontrolü', 'Sevkiyat planı', 'HACCP kontrolü'],
    benefitScore: 8,
    teamScore: 8,
  },
  {
    id: 69,
    category: 'Otomotiv',
    name: 'Oto Boyahane / Kaporta',
    scenarios: ['Günlük iş planı: 4 araç boyada, 2 kaporta düzeltme, 1 full boya', 'Renk eşleştirme: Parça boyası için orijinal renk kodu bulunacak, numune hazırlanacak', 'Sigorta işlemleri: 3 aracın hasar dosyası kapatılacak, fatura ve fotoğraflar gönderilecek'],
    templates: [{ name: 'Seans Notu', content: '📸 Sigorta Dosyası: Plaka [X] | Hasar: [detay] | Önce Fotoğraf: [✓] | Sonra Fotoğraf: [✓] | Fatura: [₺]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Davet Mesajı', content: 'Boya Formül Sistemi', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['Boya Formül Sistemi', 'Sigorta Portal', 'WhatsApp'],
    quickActions: ['Günlük iş planı', 'Renk eşleştirme', 'Sigorta işlemleri'],
    benefitScore: 7,
    teamScore: 7,
  },
  {
    id: 70,
    category: 'Lojistik & Ulaşım',
    name: 'Depo / Antrepo Yönetimi',
    scenarios: ['Sabah vardiya: Gelen mal kabul, raf yerleşimi, FIFO kontrolü, sayım raporları', 'Sipariş hazırlama: 50 sipariş paketlenecek, çıkış kontrolü ve etiketleme yapılacak', 'Alan optimizasyonu: Sezonluk ürünler için raf düzeni yeniden planlanmalı'],
    templates: [{ name: 'Stok Uyarısı', content: '📊 Stok Raporu: Toplam SKU: [X] | Doluluk: [%] | Kritik Stok: [Y ürün] | Sipariş Bekleyen: [Z]', target: 'Ekip İçi', trigger: 'Günlük / Otomatik' }, { name: 'Müşteri Bilgilendirme', content: 'WMS Yazılımı', target: 'Müşteriye', trigger: 'Olay Bazlı' }],
    integrations: ['WMS Yazılımı', 'Barkod/RF Okuyucu', 'ERP Entegrasyonu'],
    quickActions: ['Sabah vardiya', 'Sipariş hazırlama', 'Alan optimizasyonu'],
    benefitScore: 8,
    teamScore: 8,
  },
];

export const CATEGORIES: { name: string; industryIds: number[] }[] = [
  { name: 'İnşaat & Mimarlık', industryIds: [1, 2, 3, 64] },
  { name: 'Sağlık', industryIds: [4, 5, 6, 7, 60, 63, 65] },
  { name: 'Teknoloji', industryIds: [8, 9, 10, 11] },
  { name: 'Eğitim', industryIds: [12, 13, 14, 67] },
  { name: 'Gıda & Restoran', industryIds: [15, 16, 17, 68] },
  { name: 'Otomotiv', industryIds: [18, 19, 69] },
  { name: 'Hukuk & Muhasebe', industryIds: [20, 21, 22] },
  { name: 'Gayrimenkul', industryIds: [23] },
  { name: 'Güzellik & Kişisel Bakım', industryIds: [24, 25] },
  { name: 'Üretim & Sanayi', industryIds: [26, 27, 28] },
  { name: 'Lojistik & Ulaşım', industryIds: [29, 30, 61, 70] },
  { name: 'Turizm & Konaklama', industryIds: [31, 32] },
  { name: 'Tarım & Hayvancılık', industryIds: [33, 34] },
  { name: 'Spor & Fitness', industryIds: [35, 36] },
  { name: 'Temizlik & Hizmet', industryIds: [37, 38] },
  { name: 'Medya & Yaratıcı', industryIds: [39, 40, 41] },
  { name: 'Enerji & Teknik', industryIds: [42, 43, 44] },
  { name: 'Finans & Sigorta', industryIds: [45, 46] },
  { name: 'Perakende', industryIds: [47, 48, 66] },
  { name: 'Danışmanlık', industryIds: [49, 50] },
  { name: 'Sanat & Eğlence', industryIds: [51, 52] },
  { name: 'Teknik Servis', industryIds: [53, 54] },
  { name: 'Profesyonel Hizmetler', industryIds: [55, 56, 57] },
  { name: 'Otomotiv Hizmet', industryIds: [58, 59] },
  { name: 'İnsan Kaynakları', industryIds: [62] },
];

export function getIndustry(id: number): Industry | undefined {
  return INDUSTRIES.find(i => i.id === id);
}

export function getIndustryByName(name: string): Industry | undefined {
  return INDUSTRIES.find(i => i.name.toLowerCase() === name.toLowerCase());
}

export function getIndustriesByCategory(category: string): Industry[] {
  return INDUSTRIES.filter(i => i.category === category);
}

export function getIndustryContext(id: number): string {
  const ind = getIndustry(id);
  if (!ind) return '';
  return `Sektör: ${ind.name} (${ind.category})
Tipik İş Senaryoları:
${ind.scenarios.map((s, i) => `${i + 1}. ${s}`).join('\n')}
Kullanılan Araçlar: ${ind.integrations.filter(Boolean).join(', ')}`;
}

export function getTemplatesForIndustry(id: number): Industry['templates'] {
  return getIndustry(id)?.templates || [];
}

export function getQuickActionsForIndustry(id: number): string[] {
  return getIndustry(id)?.quickActions || [];
}